export interface FaqItem {
  q: string;
  a: string;
}

export const faqsData: FaqItem[] = [
  {
    q: "What is an AI Humanizer?",
    a: "An AI Humanizer is an advanced software platform designed to rewrite and polish text generated by artificial intelligence models (such as ChatGPT, Claude, and Gemini). It analyzes word pairing probability (perplexity) and sentence length distribution (burstiness) to match the natural flow and rhythm of human writing."
  },
  {
    q: "How does AI content detection work?",
    a: "AI content detectors evaluate text by measuring statistical predictability. Since large language models (LLMs) output tokens based on high mathematical probability, their prose exhibits low perplexity (predictable word choices) and low burstiness (uniform sentence structures). Scanners flag text when these markers stay above a threshold."
  },
  {
    q: "Can GPTZero detect ChatGPT-4o writing?",
    a: "Yes. GPTZero's classification models are constantly trained on GPT-4o, Claude 3.5, and Gemini outputs. They easily spot the signature vocabulary and sentence symmetry of raw drafts unless the text is humanized."
  },
  {
    q: "Can Turnitin detect AI-generated writing?",
    a: "Yes, Turnitin has a highly advanced, proprietary AI classifier integrated directly into its plagiarism checking software. It breaks down student papers into segments and calculates a synthetic likelihood score, flagging copied phrases or AI structural patterns."
  },
  {
    q: "What is GEO (Generative Engine Optimization)?",
    a: "GEO is the process of structuring and writing website content so that AI search engines (like ChatGPT Search, Gemini, Perplexity, and Claude) cite, footnote, and recommend your site in their conversational answers."
  },
  {
    q: "What is AEO (Answer Engine Optimization)?",
    a: "AEO focuses on tailoring content to provide direct, concise answers for quick featured snippets and vocal smart assistants (like Siri, Google Assistant, and Alexa). It relies heavily on structured FAQs, checklists, and summary definitions."
  },
  {
    q: "How do AI search engines crawl websites?",
    a: "AI search engines use specialized user-agents (like OAI-SearchBot or PerplexityBot) to index the web. They extract structured data, schemas, direct answers, and reputable outbound link references to construct conversational responses."
  },
  {
    q: "How does REDAI Humanizer bypass AI detectors?",
    a: "REDAI restructures synthetic text by shuffling syntax trees, varying sentence lengths (increasing burstiness), replacing predictable AI transition markers, and using context-aware vocabulary to drop AI scores to 0%."
  },
  {
    q: "Does Google search penalize AI content?",
    a: "Google's search guidelines state they reward high-quality, original content that demonstrates E-E-A-T (Experience, Expertise, Authoritativeness, and Trustworthiness), regardless of how it was produced. However, they actively penalize thin, repetitive synthetic spam."
  },
  {
    q: "Is using an AI humanizer safe for academic submissions?",
    a: "Yes, when used responsibly to check, refine, and improve the clarity of your own arguments. REDAI's Academic bypass preserves citations and data integrity while randomizing statistical patterns."
  },
  {
    q: "What is the difference between GEO and traditional SEO?",
    a: "Traditional SEO focuses on keyword density, backlinks, and domain authority to rank in Google's blue links. GEO focuses on entity relevance, factual density, and schema markup to win footnotes and citation chips in AI chatbot responses."
  },
  {
    q: "How does AEO differ from GEO?",
    a: "AEO focuses on short, direct voice-search answers and featured snippets. GEO optimized for multi-layered LLM reasoning queries that combine multiple entities and require comprehensive citation-backed research pages."
  },
  {
    q: "How do I secure citations in Perplexity?",
    a: "Provide high-factual-density content, place a clear answer summary at the top of your page, maintain fast page loads, and format data using structured tables or bullets."
  },
  {
    q: "Does REDAI offer API support?",
    a: "Yes. REDAI offers a developer API that integrates easily into your CMS, article generators, or agency dashboards, automating AI scans and humanizations in bulk."
  },
  {
    q: "Does REDAI check for plagiarism?",
    a: "Yes, we integrate an advanced plagiarism scanner that matches your output against indexed pages to guarantee your content is completely original before exporting."
  },
  {
    q: "What are REDAI's rewrite parameters?",
    a: "We offer specialized modes: Academic (formal collegiate tone), Flowing (engaging blog style), Shorten (condensed copy), Formal (corporate prose), and Custom (prompt-driven directions)."
  },
  {
    q: "What is a false positive in AI detection?",
    a: "A false positive occurs when a human-written document is misclassified as AI. This happens frequently on highly structured technical papers, essays by non-native English speakers, or formulaic reviews."
  },
  {
    q: "Can Copyleaks detect paraphrased AI text?",
    a: "Standard paraphrasers that only swap synonyms are quickly flagged by Copyleaks. REDAI bypasses Copyleaks by applying deep structural alterations to sentence structures."
  },
  {
    q: "Why is an indexable sitemap important?",
    a: "Sitemaps list all active URLs, allowing traditional search spiders and AI search agents to locate and index your articles, entity pages, and tools without missing deep directories."
  },
  {
    q: "How do E-E-A-T pages benefit my website?",
    a: "Pages like About, Contact, and Policies show Google and AI assistants that your website is owned and run by real, trustworthy entities, increasing your domain authority and recommendation scores."
  }
];
